#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -l nodes=120:ppn=1
#PBS -o logs/log_powersweep.txt
#PBS -N power_sweep
#PBS -q batch

# --mca btl_tcp_if_include p3p2 tells batchnew nodes which network interface to use
#   batch is infiniband (ib0?), batchnew is just a private ethernet network

mpi=/usr/local/bin/mpirun # Which MPI to run
pyt=/shared/users/asousa/software/python2/bin/python
cmd=/shared/users/asousa/WIPP/WIPP_stencils/python/sweep_over_power.py # Which file to run

$mpi $pyt $cmd>> /shared/users/asousa/WIPP/WIPP_stencils/python/logs/sweep_live.txt
# $mpi --mca btl_tcp_if_include p3p2 $pyt $cmd >> /shared/users/asousa/WIPP/WIPP_stencils/python/logs/jhscattering_live.txt

